version: '3.9'
services:
  backend:
    restart: always
    container_name: kpd-backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: av-kpd-backend
    ports:
      - 4000:4000
    env_file:
      - .env
    networks:
      - backend
      - frontend
    depends_on:
      - postgres

  frontend:
    container_name: kpd-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: av-kpd-frontend
    ports:
      - 8081:80
    networks:
      - frontend

  postgres:
    restart: always
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend

volumes:
  postgres_data:

networks:
  frontend:
  backend: 
